services:
  web-target:
    image: nginx:1.25-alpine
    container_name: web-target
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - web_target_logs:/var/log/nginx
    networks:
      - wazuh_net

  attacker-simulator:
    image: alpine:3.20
    container_name: attacker-simulator
    command: ["sleep", "infinity"]
    networks:
      - wazuh_net
    depends_on:
      - web-target

  wazuh-agent-1:
    build:
      context: ./agents
    container_name: wazuh-agent-1
    hostname: wazuh-agent-1-web
    environment:
      WAZUH_MANAGER: wazuh.manager
      AGENT_NAME: wazuh-agent-1-web
    volumes:
      - web_target_logs:/var/log/nginx:ro
    networks:
      - wazuh_net
    depends_on:
      - web-target

  wazuh-agent-2:
    build:
      context: ./agents
    container_name: wazuh-agent-2
    hostname: wazuh-agent-2-traffic
    environment:
      WAZUH_MANAGER: wazuh.manager
      AGENT_NAME: wazuh-agent-2-traffic
    networks:
      - wazuh_net

  wazuh-agent-3:
    build:
      context: ./agents
    container_name: wazuh-agent-3
    hostname: wazuh-agent-3-malware
    environment:
      WAZUH_MANAGER: wazuh.manager
      AGENT_NAME: wazuh-agent-3-malware
    networks:
      - wazuh_net

volumes:
  web_target_logs:

networks:
  wazuh_net:
    external: true
    name: ${WAZUH_NETWORK}
